# -*- coding: utf-8 -*-
"""object-detect-YOLOv9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y4jLH9IhFrnYTd7SBMv7WD8qpmmpctIl
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install roboflow
!git clone https://github.com/WongKinYiu/yolov9
# %cd yolov9
!pip install -r requirements.txt

import os
import torch
from IPython.display import Image, display
from roboflow import Roboflow

#dataset
rf = Roboflow(api_key="ZefU506bA4BaulmhGVFc")
project = rf.workspace("siscer-project").project("sampah-organik-dan-anorganik")
version = project.version(6)
dataset = version.download("yolov9")

#  Download pre-trained weights
!wget https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-c.pt

# training model
!python train.py \
    --batch 16 \
    --epochs 30 \
    --img 640 \
    --device 0 \
    --min-items 0 \
    --close-mosaic 15 \
    --data {dataset.location}/data.yaml \
    --weights gelan-c.pt \
    --cfg models/detect/gelan-c.yaml \
    --hyp hyp.scratch-high.yaml \
    --name waste_detection

!python val.py \
    --weights /content/yolov9/runs/train/waste_detection/weights/best.pt \
    --data {dataset.location}/data.yaml \
    --img 640 \
    --batch 16 \
    --conf 0.001 \
    --iou 0.7 \
    --device 0

!python export.py \
    --weights /content/yolov9/runs/train/waste_detection/weights/best.pt \
    --include onnx \
    --device cpu

import matplotlib.pyplot as plt
import numpy as np

# Display training results
display(Image(filename='/content/yolov9/runs/train/waste_detection/results.png'))
print("\nConfusion Matrix:")
display(Image(filename='/content/yolov9/runs/train/waste_detection/confusion_matrix.png'))

# Test deteksi pada beberapa gambar validasi
!python detect.py \
    --weights /content/yolov9/runs/train/waste_detection/weights/best.pt \
    --source {dataset.location}/valid/images \
    --img 640 \
    --conf 0.25 \
    --device 0

# Display detection results
import glob
for image_path in glob.glob('runs/detect/exp/*.jpg')[:5]:
    display(Image(filename=image_path))
    print("\n")

!zip -r waste_detection_model.zip \
    /content/yolov9/runs/train/waste_detection/weights/best.pt \
    /content/yolov9/runs/train/waste_detection/weights/best.onnx \
    /content/yolov9/Sampah-Organik-dan-Anorganik-6/data.yaml

from google.colab import drive
drive.mount('/content/drive')

# Pindahkan file zip ke Google Drive
!mv /content/yolov9/waste_detection_model.zip /content/drive/MyDrive/

